services:
  bot:
    container_name: Sport_Flow_bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      POSTGRESQL_URL: postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      - db
    volumes:
      - .:/app
    command: [ "python", "app.py" ]

  db:
    image: postgres:15
    container_name: Sport_Flow_DB
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT_HOST}:${DB_PORT}
    volumes:
      - sport_flow_pg_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    volumes:
      - ./config_local.py:/pgadmin4/config_local.py
    depends_on:
      - db
    ports:
      - "${PGADMIN_PORT_HOST}:80"
    restart: unless-stopped



volumes:
  sport_flow_pg_data:
